'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Check, ChevronDown, ChevronLeft, ChevronRight, Heart, Lock, MapPin, Menu, Search, Settings, ShoppingBag, SlidersHorizontal, Star, UserRound, X } from 'lucide-react'

const sections = [
  ['colors', 'رنگ‌ها'], ['type', 'تایپوگرافی'], ['spacing', 'فاصله‌گذاری و شبکه'], ['buttons', 'دکمه‌ها'], ['inputs', 'فرم‌ها و ورودی‌ها'], ['badges', 'نشان‌ها و برچسب‌ها'], ['cards', 'کارت‌ها'], ['navigation', 'پیمایش و ناوبری'], ['feedback', 'پوشش‌ها و هشدارها'], ['icons', 'آیکون‌ها'],
]
const colors = [['--background', '#FFFFFF', 'پس‌زمینه'], ['--foreground', '#111111', 'متن اصلی'], ['--muted', '#F6F3EF', 'سطح خنثی'], ['--text-muted', '#9A9692', 'متن کم‌رنگ'], ['--line', '#E6E3DF', 'خطوط'], ['--orange', '#E65D17', 'اکسنت DBY'], ['success', '#008C68', 'موفقیت / تخفیف'], ['danger', '#C34B42', 'خطا / حذف']]
const icons = [[Search, 'جستجو'], [ShoppingBag, 'سبد خرید'], [UserRound, 'کاربر'], [Heart, 'علاقه‌مندی'], [X, 'بستن'], [ChevronLeft, 'قبلی / RTL'], [ChevronRight, 'بعدی / RTL'], [SlidersHorizontal, 'فیلتر'], [Star, 'امتیاز'], [Check, 'تأیید'], [Lock, 'امنیت'], [MapPin, 'آدرس']]

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="ds-section"><div className="ds-section-title"><span>{String(sections.findIndex(([key]) => key === id) + 1).padStart(2, '0')}</span><h2>{title}</h2></div>{children}</section>
}
function Caption({ children }: { children: React.ReactNode }) { return <small className="ds-caption">{children}</small> }

export default function DesignSystemPage() {
  const [active, setActive] = useState('colors')
  const [loading, setLoading] = useState(false)
  const [checked, setChecked] = useState(true)
  const [menuOpen, setMenuOpen] = useState(false)
  const [tab, setTab] = useState('colors')
  return <main className="design-system-page" dir="rtl">
    <header className="ds-header"><Link href="/" className="logo">DBY</Link><div><span className="ds-kicker">INTERNAL REFERENCE</span><h1>سیستم طراحی DBY</h1></div><Link href="/" className="ds-exit">بازگشت به فروشگاه <ArrowLeft size={15} /></Link></header>
    <div className="ds-mobile-tabs">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className={active === id ? 'active' : ''} onClick={() => setActive(id)}>{label}</a>)}</div>
    <div className="ds-layout"><aside className="ds-sidebar"><div className="ds-sidebar-label">فهرست راهنما</div>{sections.map(([id, label], index) => <a key={id} href={`#${id}`} className={active === id ? 'active' : ''} onClick={() => setActive(id)}><span>{String(index + 1).padStart(2, '0')}</span>{label}</a>)}<div className="ds-note">این صفحه به منوی اصلی سایت اضافه نشده است و فقط برای تیم طراحی و توسعه در دسترس است.</div></aside>
      <div className="ds-content">
        <Section id="colors" title="رنگ‌ها"><div className="ds-color-grid">{colors.map(([name, value, label]) => <div className="ds-swatch" key={name}><div style={{ background: value }} /><strong>{label}</strong><Caption>{value} · {name}</Caption></div>)}</div></Section>
        <Section id="type" title="تایپوگرافی"><div className="ds-type-grid"><div className="ds-type-sample ds-display"><span>Display / 42px</span><strong>تجربه‌ای برای هر روز</strong><Caption>Vazirmatn · 700 · line-height 1.1</Caption></div><div className="ds-type-sample"><span>Body / 16px</span><p>لباس‌هایی با فرم ساده و کیفیت ماندگار، برای سبک شخصی شما.</p><Caption>Vazirmatn · 400 · line-height 1.8</Caption></div><div className="ds-type-sample"><span>Eyebrow / 10px</span><b className="eyebrow orange">TRENDING · ۲۰۲۶</b><Caption>uppercase · letter-spacing 4px</Caption></div><div className="ds-type-sample"><span>Link / 12px</span><a className="ds-link">مشاهده همه محصولات <ArrowLeft size={13} /></a><Caption>bold · logical spacing</Caption></div></div></Section>
        <Section id="spacing" title="فاصله‌گذاری و شبکه"><div className="ds-spacing">{[4, 8, 12, 16, 24, 32, 48, 64].map(size => <div key={size}><i style={{ width: size * 2 }} /><span>{size}px</span></div>)}</div><div className="ds-grid-demo"><div><strong>Container</strong><span>max-width: 1120px · gutter: 32px</span></div><div><strong>Product grid</strong><span>mobile 2 · tablet 3 · desktop 4 columns</span></div><div><strong>Breakpoints</strong><span>800px mobile · 1200px wide desktop</span></div></div></Section>
        <Section id="buttons" title="دکمه‌ها"><div className="ds-button-row"><button className="ds-btn primary">افزودن به سبد</button><button className="ds-btn secondary">مشاهده جزئیات</button><button className="ds-btn danger">حذف آدرس</button><button className="ds-btn" disabled>غیرفعال</button><button className="ds-btn primary" onClick={() => { setLoading(true); setTimeout(() => setLoading(false), 900) }}>{loading ? 'در حال پردازش…' : 'ذخیره تغییرات'}</button><button className="ds-icon-btn"><Heart size={17} /></button><Caption>padding از نوع ps-/pe- برای RTL · اندازه‌های default / small / full-width</Caption></div></Section>
        <Section id="inputs" title="فرم‌ها و ورودی‌ها"><div className="ds-input-grid"><label>نام و نام خانوادگی<input placeholder="مثلاً سارا احمدی" /></label><label className="error">ایمیل<input value="sara@" readOnly /><em>فرمت ایمیل صحیح نیست</em></label><label>رمز عبور<div className="ds-input-icon"><input type="password" value="password" readOnly /><button aria-label="نمایش رمز"><UserRound size={15} /></button></div></label><label>شهر<select defaultValue="تهران"><option>تهران</option><option>شیراز</option><option>اصفهان</option></select></label><label className="ds-search-field"><Search size={15} /><input placeholder="جستجو در محصولات" /></label><label className="ds-check"><input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} /> ذخیره به عنوان آدرس پیش‌فرض</label></div><div className="ds-payment"><label className="selected"><input type="radio" defaultChecked name="payment" /> پرداخت آنلاین <small>امن و سریع</small></label><label><input type="radio" name="payment" /> پرداخت در محل <small>فقط تهران</small></label></div></Section>
        <Section id="badges" title="نشان‌ها و برچسب‌ها"><div className="ds-badge-row"><b className="badge new">NEW</b><b className="badge best">BEST SELLER</b><b className="badge sale">SALE -۲۰٪</b><b className="badge premium">PREMIUM</b><b className="status processing">در حال پردازش</b><b className="status shipped">ارسال شده</b><b className="status delivered">تحویل داده شده</b><b className="promo-tag"><Check size={13} /> کد تخفیف اعمال شد</b></div></Section>
        <Section id="cards" title="کارت‌ها"><div className="ds-card-grid"><article className="ds-product-card"><div className="ds-product-image"><span className="badge sale">SALE</span></div><span>DBY / ESSENTIALS</span><h3>پیراهن لینن آزاد</h3><strong>۲,۴۹۰,۰۰۰ تومان</strong><del>۳,۱۰۰,۰۰۰</del></article><article className="ds-category-card"><span>01 / 06</span><strong>پیراهن و تاپ</strong></article><article className="ds-address-card"><div><MapPin size={15} /><strong>خانه</strong><b>پیش‌فرض</b></div><p>تهران، خیابان ولیعصر، کوچه ۲۴<br />پلاک ۱۲، واحد ۴</p><button>ویرایش آدرس</button></article><article className="ds-order-card"><div><span>پیراهن لینن آزاد · ۲ عدد</span><strong>۴,۹۸۰,۰۰۰ تومان</strong></div><Caption>line item / order summary</Caption></article></div></Section>
        <Section id="navigation" title="پیمایش و ناوبری"><div className="ds-nav-demo"><div className="ds-fake-header"><span className="logo">DBY</span><a className="active">محصولات</a><a>تازه‌ها</a><a>درباره ما</a><button><Search size={16} /></button><button><UserRound size={16} /></button><button><ShoppingBag size={16} /></button></div><div className="ds-breadcrumb"><span>خانه</span><ChevronLeft size={13} /><b>محصولات</b><ChevronLeft size={13} /><strong>پیراهن</strong></div><div className="ds-stepper"><b>۱ سبد خرید</b><i /><span>۲ اطلاعات ارسال</span><i /><span>۳ پرداخت</span></div></div><Caption>آیکون‌های chevron در RTL با جهت منطقی mirror می‌شوند.</Caption></Section>
        <Section id="feedback" title="پوشش‌ها و هشدارها"><div className="ds-feedback-grid"><button className="ds-overlay-trigger" onClick={() => setMenuOpen(!menuOpen)}><Menu size={18} /> باز کردن منوی نمونه</button>{menuOpen && <div className="ds-dropdown"><strong>حساب کاربری</strong><a>سفارش‌های من</a><a>آدرس‌ها</a><a>خروج از حساب</a></div>}<div className="ds-success"><Check size={17} /> سفارش با موفقیت ثبت شد</div><div className="ds-error"><X size={17} /> خطایی رخ داد. دوباره تلاش کنید.</div><div className="ds-empty"><Heart size={25} /><strong>علاقه‌مندی شما خالی است</strong><button className="ds-btn secondary">مشاهده محصولات</button></div></div></Section>
        <Section id="icons" title="آیکون‌ها"><div className="ds-icon-grid">{icons.map(([Icon, label]) => <div key={label as string}><span><Icon size={19} /></span><b>{label as string}</b></div>)}</div><Caption>checkmark، star و lock بدون mirror می‌مانند؛ chevronها در RTL آینه می‌شوند.</Caption></Section>
      </div>
    </div>
    <footer className="ds-footer">DBY Design System · Internal only · v1.0</footer>
  </main>
}
